services:
  db:
    container_name: screen_it_db
    image: bitnami/postgresql:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    container_name: screen_it_app
    build: .
    restart: unless-stopped
    depends_on:
      - db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # App Config
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      # Database Config
      - DATABASE_URL=${DATABASE_URL}
      # Better Auth Config
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      # Admin user and seed config
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SKIP_ADMIN_IF_EXISTS=${SKIP_ADMIN_IF_EXISTS}
      # Bot url
      - BOT_BASE_URL=${BOT_BASE_URL}

    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:2000/api || exit 1']
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  db_data:
    driver: local
